version: '3'

services:
  syncthing:
    image: syncthing/syncthing:1.23
    restart: unless-stopped
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./zettelkasten:/var/syncthing:z
    container_name: syncthing